### PR TITLE
SS-8135

### PR DESCRIPTION
**Pull request by MajorMeerkatThe3rd**
@snabela nothing to review yet, just WIP if you want to have a look already

### CODE REVIEW

**Comment by snabela** [comment]
> @snabela nothing to review yet, just WIP if you want to have a look already

@MajorMeerkatThe3rd many thanks, checked it out!

**Comment by MajorMeerkatThe3rd** [comment]
@snabela If you have a second, please tell me what you think about the last commits, no rush!

**Comment by snabela** [comment]
> @snabela If you have a second, please tell me what you think about the last commits, no rush!
> 
> With the last commit and the access function store, they are now disconnected from the viewport and can even exist in the model state in a headless fashion. For WebGI these functions could be provided by the WebGI implementation

@MajorMeerkatThe3rd many thanks! I think this looks very good!

**Comment by MajorMeerkatThe3rd** [comment]
@snabela I don't think there will be more changes needed in the shared repo, so this is ready for review. no rush!

**Pull request merged**
